=== kris18shadow/AutoShowRoom/AutoShowRoom/XmlFiles/AutoShowRoom.dtd
<!ELEMENT auto-showroom (showroomName, cars, employees, orders?) >
<!ELEMENT showroomName (#PCDATA) >
<!ELEMENT cars (car+) >
<!ELEMENT employees (employee+) >
<!ELEMENT orders (order*) >

<!ELEMENT car (brand, model, power, fuel, description, class, price, color, weight, safety-rating, seats) >
<!ELEMENT brand (#PCDATA) >
<!ELEMENT model (#PCDATA) >
<!ELEMENT power (#PCDATA) >
<!ELEMENT fuel (#PCDATA) >
<!ELEMENT description (#PCDATA) >
<!ELEMENT class (#PCDATA) >
<!ELEMENT price (#PCDATA) >
<!ELEMENT color (#PCDATA) >
<!ELEMENT weight (#PCDATA) >
<!ELEMENT safety-rating (#PCDATA) >
<!ELEMENT seats (#PCDATA) >

<!ELEMENT employee (employee-name, employee-salary, employee-position) >
<!ELEMENT employee-name (#PCDATA) >
<!ELEMENT employee-salary (#PCDATA) >
<!ELEMENT employee-position (#PCDATA) >

<!ELEMENT order (order-date, total-price, client-info) >
<!ELEMENT order-date (#PCDATA) >
<!ELEMENT total-price (#PCDATA) >
<!ELEMENT client-info (client-name, client-address, client-telephone?) >
<!ELEMENT client-name (#PCDATA) >
<!ELEMENT client-telephone (#PCDATA) >
<!ELEMENT client-address (city, address) >
<!ELEMENT city (#PCDATA) >
<!ELEMENT address (#PCDATA) >

<!ATTLIST car car-id ID #REQUIRED 
              added-by IDREF #REQUIRED
              in-stock (t|f) #REQUIRED
              new (t|f) #REQUIRED
              total-orders CDATA   #REQUIRED
              country-of-origin CDATA #REQUIRED>

<!ATTLIST employee employee-id ID #REQUIRED >

<!ATTLIST order order-id ID #REQUIRED
                ordered-products IDREFS #REQUIRED
                processed-by IDREF #REQUIRED>

=== kris18shadow/AutoShowRoom/AutoShowRoom/XmlFiles/AutoShowRoom-13.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE auto-showroom SYSTEM "AutoShowRoom.dtd">
<auto-showroom>
    <showroomName>ФърстАуто</showroomName>
    <cars>
        <car car-id="a13-c101" added-by="a13-e3" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Япония">
            <brand>Митсубиши</brand>
            <model>Еклипс</model>
            <power>224 к.с.</power>
            <fuel>бензин</fuel>
            <description>Японски спортен автомобил.</description>
            <class>купе</class>
            <price>9500 лв.</price>
			<color>сив</color>
			<weight>1320 кг.</weight>
			<safety-rating> 4/5 </safety-rating>
            <seats>2</seats>
        </car>
        <car car-id="a13-c102" added-by="a13-e2" in-stock="f" new = "f" total-orders = "2" country-of-origin = "САЩ">
            <brand>Шефролет</brand>
            <model>Камаро</model>
            <power>390 к.с.</power>
            <fuel>бензин</fuel>
            <description>Американска спортна кола.</description>
            <class>купе</class>
            <price>24500 лв.</price>
			<color>сив</color>
			<weight>1720 кг.</weight>
			<safety-rating> 2/5 </safety-rating>
            <seats>4</seats>
        </car>
        <car car-id="a13-c103" added-by="a13-e2" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Германия">
            <brand>Порше</brand>
            <model>Бокстър</model>
            <power>280 к.с.</power>
            <fuel>бензин</fuel>
            <description>Спортен немски кабриолет.</description>
            <class>кабрио</class>
            <price>110000 лв.</price>
			<color>сив</color>
			<weight>1320 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>2</seats>
        </car>
        <car car-id="a13-c104" added-by="a13-e1" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Германия">
            <brand>Ауди</brand>
            <model>Ар8</model>
            <power>267 к.с.</power>
            <fuel>бензин</fuel>
            <description>Луксозно спортно кабрио.</description>
            <class>купе</class>
            <price>165000 лв.</price>
			<color>сив</color>
			<weight>1520 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>2</seats>
        </car> 
        <car car-id="a13-c105" added-by="a13-e1" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Германия">
            <brand>Порше</brand>
            <model>Кайен</model>
            <power>385 к.с.</power>
            <fuel>бензин</fuel>
            <description>Немски луксозен джип.</description>
            <class>джип</class>
            <price>110000 лв.</price>
			<color>сив</color>
			<weight>1920 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>5</seats>
        </car>
    </cars>
    <employees>
        <employee employee-id="a13-e1">
            <employee-name>Иван Стоянов</employee-name>
			<employee-salary> 4500 лв.</employee-salary>
            <employee-position>собственик</employee-position>
        </employee>
        <employee employee-id="a13-e2">
            <employee-name>Петър Сосков</employee-name>
			<employee-salary> 3500 лв.</employee-salary>
            <employee-position>мениджър</employee-position>
        </employee>
        <employee employee-id="a13-e3">
            <employee-name>Стоян Крайчовски</employee-name>
			<employee-salary> 3500 лв.</employee-salary>
            <employee-position>механик</employee-position>
        </employee>
    </employees>
    <orders>        
        <order order-id="a13-or1" ordered-products="a13-c102" processed-by="a13-e2">
            <order-date>01.01.2016</order-date>
            <total-price>24500лв.</total-price>
            <client-info>
                <client-name>Стоян Иванов</client-name>
                <client-address>
                    <city>Бургас</city>
                    <address>жк.Бели ливади, бл17Б ет.5 ап.42</address>
                </client-address>
                <client-telephone>087763852</client-telephone>
            </client-info>
        </order>
    </orders>
</auto-showroom>

=== kris18shadow/AutoShowRoom/AutoShowRoom/XmlFiles/AutoShowRoom-10.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE auto-showroom SYSTEM "AutoShowRoom.dtd">
<auto-showroom>
    <showroomName>ТопАуто</showroomName>
    <cars>
        <car car-id="a10-c101" added-by="a10-e2" in-stock="t" new = "t" total-orders = "3" country-of-origin = "САЩ">
            <brand>Форд</brand>
            <model>ДжиТи</model>
            <power>400 к.с.</power>
            <fuel>безнзин</fuel>
            <description>Спортен американски автомобил.</description>
            <class>купе</class>
            <price>155500 лв.</price>
			<color>черен</color>
			<weight>1320 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>5</seats>
        </car>
        <car car-id="a10-c102" added-by="a10-e2" in-stock="f" new = "t" total-orders = "1" country-of-origin = "Великобритания">
            <brand>Ягуар</brand>
            <model>ЕксДжей</model>
            <power>250 к.с.</power>
            <fuel>бензин</fuel>
            <description>Спортно олекотено кабрио.</description>
            <class>кабрио</class>
            <price>44500 лв.</price>
			<color>жилт</color>
			<weight>1020 кг.</weight>
			<safety-rating> 4/5 </safety-rating>
            <seats>2</seats>
        </car>
        <car car-id="a10-c103" added-by="a10-e2" in-stock="t" new = "t" total-orders = "2" country-of-origin = "Великобритания">
            <brand>Астън Мартин</brand>
            <model>Вантидж</model>
            <power>384 к.с.</power>
            <fuel>бензин</fuel>
            <description>Британска спортна кола с две врати.</description>
            <class>купе</class>
            <price>150000 лв.</price>
			<color>бял</color>
			<weight>1220 кг.</weight>
			<safety-rating> 4/5 </safety-rating>
            <seats>2</seats>
        </car>        
    </cars>
    <employees>
        <employee employee-id="a10-e1">
            <employee-name>Иван Иванов</employee-name>
			<employee-salary> 4500 лв.</employee-salary>
            <employee-position>собственик</employee-position>
        </employee>
        <employee employee-id="a10-e2">
            <employee-name>Георги Методиев</employee-name>
			<employee-salary> 4500 лв.</employee-salary>
            <employee-position>мениджър</employee-position>
        </employee>       
    </employees>
    <orders>        
        <order order-id="a10-or1" ordered-products="a10-c102" processed-by="a10-e2">
            <order-date>27.12.2015</order-date>
            <total-price>44500лв.</total-price>
            <client-info>
                <client-name>Бойко Борисов</client-name>
                <client-address>
                    <city>София</city>
                    <address>жк.Бояна, ул. Бяла бреза номер 14</address>
                </client-address>
                <client-telephone>088234559</client-telephone>
            </client-info>
        </order>
    </orders>
</auto-showroom>

=== kris18shadow/AutoShowRoom/AutoShowRoom/XmlFiles/AutoShowRoom-7.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE auto-showroom SYSTEM "AutoShowRoom.dtd">
<auto-showroom>
    <showroomName>МегаАуто</showroomName>
    <cars>
        <car car-id="a7-c101" added-by="a7-e2" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Германия">
            <brand>Ауди</brand>
            <model>А6</model>
            <power>150 к.с.</power>
            <fuel>бензин</fuel>
            <description>Просторна семейна кола с голям багажник.</description>
            <class>седан</class>
            <price>6500 лв.</price>
			<color>черен</color>
			<weight>1520 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>5</seats>
        </car>
        <car car-id="a7-c102" added-by="a7-e1" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Германия">
            <brand>Ауди</brand>
            <model>А4</model>
            <power>115 к.с.</power>
            <fuel>дизел</fuel>
            <description>Евтин семеен седан.</description>
            <class>седан</class>
            <price>3500 лв.</price>
			<color>бял</color>
			<weight>1460 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>5</seats>
        </car>
        <car car-id="a7-c103" added-by="a7-e3" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Германия">
            <brand>БМВ</brand>
            <model>740</model>
            <power>325 к.с.</power>
            <fuel>бензин</fuel>
            <description>Спортен луксозен автомобил.</description>
            <class>седан</class>
            <price>14000 лв.</price>
			<color>сив</color>
			<weight>1720 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>5</seats>
        </car>
        <car car-id="a7-c104" added-by="a7-e4" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Германия">
            <brand>Мерцедес</brand>
            <model>Е200</model>
            <power>150 к.с.</power>
            <fuel>бензин</fuel>
            <description>Немски седан.</description>
            <class>седан</class>
            <price>6300 лв.</price>
			<color>сив</color>
			<weight>1520 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>5</seats>
        </car> 
        <car car-id="a7-c105" added-by="a7-e1" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Чехия">
            <brand>Шкода</brand>
            <model>Октавия</model>
            <power>100 к.с.</power>
            <fuel>дизел</fuel>
            <description>Евтина и икономична алтернатива.</description>
            <class>седан</class>
            <price>1900 лв.</price>
			<color>червен</color>
			<weight>1470 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>5</seats>
        </car>
    </cars>
    <employees>
        <employee employee-id="a7-e1">
            <employee-name>Йордан Величков</employee-name>
			<employee-salary> 4500 лв.</employee-salary>
            <employee-position>собственик</employee-position>
        </employee>
        <employee employee-id="a7-e2">
            <employee-name>Радостин Петканов</employee-name>
			<employee-salary> 3500 лв.</employee-salary>
            <employee-position>мениджър</employee-position>
        </employee>
        <employee employee-id="a7-e3">
            <employee-name>Иван Райков</employee-name>
			<employee-salary> 1500 лв.</employee-salary>
            <employee-position>асистент</employee-position>
        </employee>
        <employee employee-id="a7-e4">
            <employee-name>Стилян Петров</employee-name>
			<employee-salary> 1500 лв.</employee-salary>
            <employee-position>асистент</employee-position>
        </employee>
        <employee employee-id="a7-e5">
            <employee-name>Ибрахим Михайлов</employee-name>
			<employee-salary> 1500 лв.</employee-salary>
            <employee-position>механик</employee-position>
        </employee>
    </employees>
    <orders>
        <order order-id="a7-or1" ordered-products="a7-c102" processed-by="a7-e3">
            <order-date>11.12.2015</order-date>
            <total-price>3500 лв.</total-price>
            <client-info>
                <client-name>Петър Петранов</client-name>
                <client-address>
                    <city>София</city>
                    <address>жк.Драгалевци, бл125А ет.2 ап.13</address>
                </client-address>
                <client-telephone>0888852355</client-telephone>
            </client-info>
        </order>
        <order order-id="a7-or2" ordered-products="a7-c104" processed-by="a7-e3">
            <order-date>14.12.2015</order-date>
            <total-price>6300 лв.</total-price>
            <client-info>
                <client-name>Веско Мирков</client-name>
                <client-address>
                    <city>Пловдив</city>
                    <address>жк.Права ливада, бл12А ет.1 ап.2</address>
                </client-address>
                <client-telephone>087212455</client-telephone>
            </client-info>
        </order>
    </orders>
</auto-showroom>

=== kris18shadow/AutoShowRoom/AutoShowRoom/XmlFiles/AutoShowRoom-2.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE auto-showroom SYSTEM "AutoShowRoom.dtd">
<auto-showroom>
    <showroomName>АутоПлюс</showroomName>
    <cars>
        <car car-id="a2-c101" added-by="a2-e2" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Германия">
            <brand>БМВ</brand>
            <model>520</model>
            <power>150 к.с.</power>
            <fuel>бензин</fuel>
            <description>Просторна семейна кола с голям багажник и мощен двигател.</description>
            <class>седан</class>
            <price>6500 лв.</price>
			<color>сив</color>
			<weight>1520 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>5</seats>
        </car>
        <car car-id="a2-c102" added-by="a2-e1" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Германия">
            <brand>Форд</brand>
            <model>Мондео</model>
            <power>115 к.с.</power>
            <fuel>дизел</fuel>
            <description>Евтин семеен седан.</description>
            <class>седан</class>
            <price>3500 лв.</price>
			<color>бял</color>
			<weight>1460 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>5</seats>
        </car>
        <car car-id="a2-c103" added-by="a2-e3" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Германия">
            <brand>БМВ</brand>
            <model>740</model>
            <power>325 к.с.</power>
            <fuel>бензин</fuel>
            <description>Спортен луксозен автомобил.</description>
            <class>седан</class>
            <price>14000 лв.</price>
			<color>сив</color>
			<weight>1720 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>5</seats>
        </car>
        <car car-id="a2-c104" added-by="a2-e4" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Германия">
            <brand>Мерцедес</brand>
            <model>Ц200</model>
            <power>135 к.с.</power>
            <fuel>бензин</fuel>
            <description>Малък немски седан.</description>
            <class>седан</class>
            <price>6300 лв.</price>
			<color>сив</color>
			<weight>1520 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>5</seats>
        </car> 
        <car car-id="a2-c105" added-by="a2-e1" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Германия">
            <brand>Шкода</brand>
            <model>Октавия</model>
            <power>100 к.с.</power>
            <fuel>дизел</fuel>
            <description>Евтина и икономична алтернатива.</description>
            <class>седан</class>
            <price>1900 лв.</price>
			<color>червен</color>
			<weight>1470 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>5</seats>
        </car>
    </cars>
    <employees>
        <employee employee-id="a2-e1">
            <employee-name>Александър Белгийски</employee-name>
			<employee-salary> 4500 лв.</employee-salary>
            <employee-position>собственик</employee-position>
        </employee>
        <employee employee-id="a2-e2">
            <employee-name>Васил Петканов</employee-name>
			<employee-salary> 3500 лв.</employee-salary>
            <employee-position>мениджър</employee-position>
        </employee>
        <employee employee-id="a2-e3">
            <employee-name>Асен Миноров</employee-name>
			<employee-salary> 1500 лв.</employee-salary>
            <employee-position>асистент</employee-position>
        </employee>
        <employee employee-id="a2-e4">
            <employee-name>Божан Петров</employee-name>
			<employee-salary> 1500 лв.</employee-salary>
            <employee-position>асистент</employee-position>
        </employee>
        <employee employee-id="a2-e5">
            <employee-name>Валентин Михайлов</employee-name>
			<employee-salary> 1500 лв.</employee-salary>
            <employee-position>механик</employee-position>
        </employee>
    </employees>
    <orders>
        <order order-id="two-or1" ordered-products="a2-c102" processed-by="a2-e3">
            <order-date>11.12.2015</order-date>
            <total-price>3500 лв.</total-price>
            <client-info>
                <client-name>Георги Петранов</client-name>
                <client-address>
                    <city>София</city>
                    <address>жк.Красно село, бл125А ет.2 ап.13</address>
                </client-address>
                <client-telephone>0888152355</client-telephone>
            </client-info>
        </order>
        <order order-id="two-or2" ordered-products="a2-c104" processed-by="a2-e3">
            <order-date>14.12.2015</order-date>
            <total-price>6300 лв.</total-price>
            <client-info>
                <client-name>Веско Мирков</client-name>
                <client-address>
                    <city>Пловдив</city>
                    <address>жк.Права ливада, бл12А ет.1 ап.2</address>
                </client-address>
                <client-telephone>087252455</client-telephone>
            </client-info>
        </order>
    </orders>
</auto-showroom>

=== kris18shadow/AutoShowRoom/AutoShowRoom/XmlFiles/AutoShowRoom-14.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE auto-showroom SYSTEM "AutoShowRoom.dtd">
<auto-showroom>
    <showroomName>УралАвто</showroomName>
    <cars>
        <car car-id="a14-c101" added-by="a14-e3" in-stock="t" new = "t" total-orders = "2" country-of-origin = "Германия">
            <brand>Мерцедес</brand>
            <model>Ц320АМГ</model>
            <power>355 к.с.</power>
            <fuel>бензин</fuel>
            <description>Луксозен седан.</description>
            <class>седан</class>
            <price>75500 лв.</price>
			<color>черен</color>
			<weight>1820 кг.</weight>
			<safety-rating> 4/5 </safety-rating>
            <seats>5</seats>
        </car>
        <car car-id="a14-c102" added-by="a14-e4" in-stock="t" new = "f" total-orders = "1" country-of-origin = "САЩ">
            <brand>Форд</brand>
            <model>Мондео</model>
            <power>190 к.с.</power>
            <fuel>дизел</fuel>
            <description>Американски просторен седан.</description>
            <class>седан</class>
            <price>6500 лв.</price>
			<color>бял</color>
			<weight>1720 кг.</weight>
			<safety-rating> 4/5 </safety-rating>
            <seats>5</seats>
        </car>
        <car car-id="a14-c103" added-by="a14-e2" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Германия">
            <brand>БМВ</brand>
            <model>Екс3</model>
            <power>240 к.с.</power>
            <fuel>бензин</fuel>
            <description>Немски офроудър с икономичен двигател.</description>
            <class>джип</class>
            <price>18000 лв.</price>
			<color>червен</color>
			<weight>1620 кг.</weight>
			<safety-rating> 4/5 </safety-rating>
            <seats>5</seats>
        </car>
        <car car-id="a14-c104" added-by="a14-e1" in-stock="t" new = "f" total-orders = "3" country-of-origin = "Япония">
            <brand>Нисан</brand>
            <model>Алмера</model>
            <power>160 к.с.</power>
            <fuel>дизел</fuel>
            <description>Здрав и голям японски седан.</description>
            <class>седан</class>
            <price>15000 лв.</price>
			<color>сив</color>
			<weight>1320 кг.</weight>
			<safety-rating> 4/5 </safety-rating>
            <seats>5</seats>
        </car> 
        <car car-id="a14-c105" added-by="a14-e1" in-stock="t" new = "f" total-orders = "2" country-of-origin = "САЩ">
            <brand>Шевролет</brand>
            <model>Малибу</model>
            <power>385 к.с.</power>
            <fuel>бензин</fuel>
            <description>Американски седан с голям двигател.</description>
            <class>седан</class>
            <price>110000 лв.</price>
			<color>зелен</color>
			<weight>1320 кг.</weight>
			<safety-rating> 4/5 </safety-rating>
            <seats>5</seats>
        </car>
    </cars>
    <employees>
        <employee employee-id="a14-e1">
            <employee-name>Петър Иванов</employee-name>
			<employee-salary> 4500 лв.</employee-salary>
            <employee-position>собственик</employee-position>
        </employee>
        <employee employee-id="a14-e2">
            <employee-name>Петър Сърменов</employee-name>
			<employee-salary> 3500 лв.</employee-salary>
            <employee-position>мениджър</employee-position>
        </employee>
        <employee employee-id="a14-e3">
            <employee-name>Ивайло Василев</employee-name>
			<employee-salary> 1500 лв.</employee-salary>
            <employee-position>асистент</employee-position>
        </employee>
        <employee employee-id="a14-e4">
            <employee-name>Асен Павлов</employee-name>
			<employee-salary> 1500 лв.</employee-salary>
            <employee-position>механик</employee-position>
        </employee>
        <employee employee-id="a14-e5">
            <employee-name>Йордан Стоименов</employee-name>
			<employee-salary> 1500 лв.</employee-salary>
            <employee-position>механик</employee-position>
        </employee>
    </employees>
    <orders>        
    </orders>
</auto-showroom>

=== kris18shadow/AutoShowRoom/AutoShowRoom/XmlFiles/AutoShowRoom-17.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE auto-showroom SYSTEM "AutoShowRoom.dtd">
<auto-showroom>
    <showroomName>АутоШампион</showroomName>
    <cars>
        <car car-id="a17-c101" added-by="a17-e2" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Германия">
            <brand>Мерцедес</brand>
            <model>Е300</model>
            <power>250 к.с.</power>
            <fuel>бензин</fuel>
            <description>Просторна семейна кола с голям багажник и мощен двигател.</description>
            <class>седан</class>
            <price>6500 лв.</price>
			<color>сив</color>
			<weight>1520 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>5</seats>
        </car>
        <car car-id="a17-c102" added-by="a17-e1" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Германия">
            <brand>Ауди</brand>
            <model>А3</model>
            <power>115 к.с.</power>
            <fuel>дизел</fuel>
            <description>Евтин семеен седан.</description>
            <class>седан</class>
            <price>3500 лв.</price>
			<color>бял</color>
			<weight>1460 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>5</seats>
        </car>
        <car car-id="a17-c103" added-by="a17-e3" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Германия">
            <brand>БМВ</brand>
            <model>740</model>
            <power>325 к.с.</power>
            <fuel>бензин</fuel>
            <description>Спортен луксозен автомобил.</description>
            <class>седан</class>
            <price>14000 лв.</price>
			<color>сив</color>
			<weight>1720 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>5</seats>
        </car>
        <car car-id="a17-c104" added-by="a17-e4" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Германия">
            <brand>Мерцедес</brand>
            <model>Ц200</model>
            <power>135 к.с.</power>
            <fuel>бензин</fuel>
            <description>Малък немски седан.</description>
            <class>седан</class>
            <price>6300 лв.</price>
			<color>сив</color>
			<weight>1520 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>5</seats>
        </car> 
        <car car-id="a17-c105" added-by="a17-e1" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Германия">
            <brand>Фолксваген</brand>
            <model>Пасат</model>
            <power>100 к.с.</power>
            <fuel>дизел</fuel>
            <description>Евтина и икономична алтернатива.</description>
            <class>седан</class>
            <price>1900 лв.</price>
			<color>червен</color>
			<weight>1470 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>5</seats>
        </car>
    </cars>
    <employees>
        <employee employee-id="a17-e1">
            <employee-name>Петър Иванов</employee-name>
			<employee-salary> 4500 лв.</employee-salary>
            <employee-position>собственик</employee-position>
        </employee>
        <employee employee-id="a17-e2">
            <employee-name>Йордан Петканов</employee-name>
			<employee-salary> 3500 лв.</employee-salary>
            <employee-position>мениджър</employee-position>
        </employee>
        <employee employee-id="a17-e3">
            <employee-name>Асен Миноров</employee-name>
			<employee-salary> 1500 лв.</employee-salary>
            <employee-position>асистент</employee-position>
        </employee>
        <employee employee-id="a17-e4">
            <employee-name>Християн Петров</employee-name>
			<employee-salary> 1500 лв.</employee-salary>
            <employee-position>асистент</employee-position>
        </employee>
        <employee employee-id="a17-e5">
            <employee-name>Валентин Михайлов</employee-name>
			<employee-salary> 1500 лв.</employee-salary>
            <employee-position>механик</employee-position>
        </employee>
    </employees>
    <orders>
        <order order-id="a17-or1" ordered-products="a17-c102" processed-by="a17-e3">
            <order-date>11.12.2015</order-date>
            <total-price>3500 лв.</total-price>
            <client-info>
                <client-name>Кристиян Петранов</client-name>
                <client-address>
                    <city>София</city>
                    <address>жк.Красно село, бл125А ет.2 ап.13</address>
                </client-address>
                <client-telephone>0888152355</client-telephone>
            </client-info>
        </order>
        <order order-id="a17-or2" ordered-products="a17-c104" processed-by="a17-e3">
            <order-date>14.12.2015</order-date>
            <total-price>6300 лв.</total-price>
            <client-info>
                <client-name>Петър Мирков</client-name>
                <client-address>
                    <city>София</city>
                    <address>жк.Права ливада, бл12А ет.1 ап.2</address>
                </client-address>
                <client-telephone>087252455</client-telephone>
            </client-info>
        </order>
    </orders>
</auto-showroom>
