=== kris18shadow/AutoShowRoom/AutoShowRoom/XmlFiles/AutoShowRoom.dtd
<!ELEMENT auto-showroom (showroomName, cars, employees, orders?) >
<!ELEMENT showroomName (#PCDATA) >
<!ELEMENT cars (car+) >
<!ELEMENT employees (employee+) >
<!ELEMENT orders (order*) >

<!ELEMENT car (brand, model, power, fuel, description, class, price, color, weight, safety-rating, seats) >
<!ELEMENT brand (#PCDATA) >
<!ELEMENT model (#PCDATA) >
<!ELEMENT power (#PCDATA) >
<!ELEMENT fuel (#PCDATA) >
<!ELEMENT description (#PCDATA) >
<!ELEMENT class (#PCDATA) >
<!ELEMENT price (#PCDATA) >
<!ELEMENT color (#PCDATA) >
<!ELEMENT weight (#PCDATA) >
<!ELEMENT safety-rating (#PCDATA) >
<!ELEMENT seats (#PCDATA) >

<!ELEMENT employee (employee-name, employee-salary, employee-position) >
<!ELEMENT employee-name (#PCDATA) >
<!ELEMENT employee-salary (#PCDATA) >
<!ELEMENT employee-position (#PCDATA) >

<!ELEMENT order (order-date, total-price, client-info) >
<!ELEMENT order-date (#PCDATA) >
<!ELEMENT total-price (#PCDATA) >
<!ELEMENT client-info (client-name, client-address, client-telephone?) >
<!ELEMENT client-name (#PCDATA) >
<!ELEMENT client-telephone (#PCDATA) >
<!ELEMENT client-address (city, address) >
<!ELEMENT city (#PCDATA) >
<!ELEMENT address (#PCDATA) >

<!ATTLIST car car-id ID #REQUIRED 
              added-by IDREF #REQUIRED
              in-stock (t|f) #REQUIRED
              new (t|f) #REQUIRED
              total-orders CDATA   #REQUIRED
              country-of-origin CDATA #REQUIRED>

<!ATTLIST employee employee-id ID #REQUIRED >

<!ATTLIST order order-id ID #REQUIRED
                ordered-products IDREFS #REQUIRED
                processed-by IDREF #REQUIRED>

=== kris18shadow/AutoShowRoom/AutoShowRoom/XmlFiles/AutoShowRoom-6.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE auto-showroom SYSTEM "AutoShowRoom.dtd">
<auto-showroom>
    <showroomName>АутоШоп</showroomName>
    <cars>
        <car car-id="a6-c101" added-by="a6-e3" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Италия">
            <brand>Алфа Ромео</brand>
            <model>147</model>
            <power>155 к.с.</power>
            <fuel>бензин</fuel>
            <description>Малка семейна кола.</description>
            <class>хетчбек</class>
            <price>4500 лв.</price>
            <color>сив</color>
			<weight>1220 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
			<seats>5</seats>
        </car>
        <car car-id="a6-c102" added-by="a6-e4" in-stock="f"  new = "f" total-orders = "1" country-of-origin = "Германия">
            <brand>фолксваген</brand>
            <model>Голф</model>
            <power>90 к.с.</power>
            <fuel>дизел</fuel>
            <description>Малък немски автомобил.</description>
            <class>хетчбек</class>
            <price>4500 лв.</price>
			<color>син</color>
			<weight>1420 кг.</weight>
			<safety-rating> 4/5 </safety-rating>
            <seats>5</seats>
        </car>
        <car car-id="a6-c103" added-by="a6-e2" in-stock="t"  new = "f" total-orders = "1" country-of-origin = "Германия">
            <brand>БМВ</brand>
            <model>М3</model>
            <power>325 к.с.</power>
            <fuel>бензин</fuel>
            <description>Спортна кола с две врати.</description>
            <class>купе</class>
            <price>11000 лв.</price>
			<color>бял</color>
			<weight>1540 кг.</weight>
			<safety-rating> 4/5 </safety-rating>
            <seats>4</seats>
        </car>
        <car car-id="a6-c104" added-by="a6-e1" in-stock="t" new = "t" total-orders = "5" country-of-origin = "Германия">
            <brand>Мерцедес</brand>
            <model>S500</model>
            <power>367 к.с.</power>
            <fuel>бензин</fuel>
            <description>Луксозен седан с високо ниво на оборудване.</description>
            <class>седан</class>
            <price>15000 лв.</price>
			<color>сив</color>
			<weight>1550 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>5</seats>
        </car> 
        <car car-id="a6-c105" added-by="a6-e1" in-stock="f" new = "t" total-orders = "1" country-of-origin = "Германия">
            <brand>Порше</brand>
            <model>Cayman</model>
            <power>285 к.с.</power>
            <fuel>бензин</fuel>
            <description>Супер-спортна кола със задно-разположен вдигател.</description>
            <class>купе</class>
            <price>70000 лв.</price>
			<color>сив</color>
			<weight>1320 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>2</seats>
        </car>
    </cars>
    <employees>
        <employee employee-id="a6-e1">
            <employee-name>Иван Василев</employee-name>
			<employee-salary> 4500 лв.</employee-salary>
            <employee-position>собственик</employee-position>
        </employee>
        <employee employee-id="a6-e2">
            <employee-name>Пламен Илиев</employee-name>
			<employee-salary> 2500 лв.</employee-salary>
            <employee-position>мениджър</employee-position>
        </employee>
        <employee employee-id="a6-e3">
            <employee-name>Боян Демирев</employee-name>
			<employee-salary> 1500 лв.</employee-salary>
            <employee-position>асистент</employee-position>
        </employee>
        <employee employee-id="a6-e4">
            <employee-name>Борис Николов</employee-name>
			<employee-salary> 1500 лв.</employee-salary>
            <employee-position>асистент</employee-position>
        </employee>
        <employee employee-id="a6-e5">
            <employee-name>Пламен Стоименов</employee-name>
			<employee-salary> 2500 лв.</employee-salary>
            <employee-position>механик</employee-position>
        </employee>
    </employees>
    <orders>
        <order order-id="six-or1" ordered-products="a6-c105" processed-by="a6-e4">
            <order-date>11.12.2015</order-date>
            <total-price>70000 лв.</total-price>
            <client-info>
                <client-name>Георги Пламенов</client-name>
                <client-address>
                    <city>София</city>
                    <address>жк.Дианабад, бл137А ет.4 ап.13</address>
                </client-address>
                <client-telephone>0888851455</client-telephone>
            </client-info>
        </order>
        <order order-id="six-or2" ordered-products="a6-c102" processed-by="a6-e4">
            <order-date>14.12.2015</order-date>
            <total-price>4500лв.</total-price>
            <client-info>
                <client-name>Иван Василев</client-name>
                <client-address>
                    <city>София</city>
                    <address>жк.Бели брези, бл127А ет.1 ап.2</address>
                </client-address>
                <client-telephone>087256355</client-telephone>
            </client-info>
        </order>
    </orders>
</auto-showroom>

=== kris18shadow/AutoShowRoom/AutoShowRoom/XmlFiles/AutoShowRoom-1.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE auto-showroom SYSTEM "AutoShowRoom.dtd">
<auto-showroom>
  <showroomName>АутоЕдно</showroomName>
  <cars>
    <car car-id="a1-c101" added-by="a1-e3" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Италия">
      <brand>Алфа Ромео</brand>
      <model>166</model>
      <power>155 к.с.</power>
      <fuel>бензин</fuel>
      <description>Просторна семейна кола с голям багажник.</description>
      <class>седан</class>
      <price>5500 лв.</price>
      <color>сив</color>
      <weight>1420 кг.</weight>
      <safety-rating> 5/5 </safety-rating>
      <seats>5</seats>
    </car>
    <car car-id="a1-c102" added-by="a1-e4" in-stock="f"  new = "f" total-orders = "1" country-of-origin = "Германия">
      <brand>Форд</brand>
      <model>Галакси</model>
      <power>90 к.с.</power>
      <fuel>дизел</fuel>
      <description>Просторен висок семеен минибус.</description>
      <class>минибус</class>
      <price>4500 лв.</price>
      <color>син</color>
      <weight>1620 кг.</weight>
      <safety-rating> 3/5 </safety-rating>
      <seats>7</seats>
    </car>
    <car car-id="a1-c103" added-by="a1-e2" in-stock="t"  new = "f" total-orders = "1" country-of-origin = "Германия">
      <brand>БМВ</brand>
      <model>М3</model>
      <power>325 к.с.</power>
      <fuel>бензин</fuel>
      <description>Спортна кола с две врати.</description>
      <class>купе</class>
      <price>11000 лв.</price>
      <color>бял</color>
      <weight>1540 кг.</weight>
      <safety-rating> 4/5 </safety-rating>
      <seats>4</seats>
    </car>
    <car car-id="a1-c104" added-by="a1-e1" in-stock="t" new = "t" total-orders = "5" country-of-origin = "Германия">
      <brand>Мерцедес</brand>
      <model>Е350</model>
      <power>267 к.с.</power>
      <fuel>бензин</fuel>
      <description>Луксозен седан с високо ниво на оборудване.</description>
      <class>седан</class>
      <price>15000 лв.</price>
      <color>сив</color>
      <weight>1550 кг.</weight>
      <safety-rating> 5/5 </safety-rating>
      <seats>5</seats>
    </car>
    <car car-id="a1-c105" added-by="a1-e1" in-stock="f" new = "t" total-orders = "1" country-of-origin = "Германия">
      <brand>Порше</brand>
      <model>911</model>
      <power>385 к.с.</power>
      <fuel>бензин</fuel>
      <description>Супер-спортна кола със задно-разположен вдигател.</description>
      <class>купе</class>
      <price>110000 лв.</price>
      <color>сив</color>
      <weight>1320 кг.</weight>
      <safety-rating> 5/5 </safety-rating>
      <seats>2</seats>
    </car>
  </cars>
  <employees>
    <employee employee-id="a1-e1">
      <employee-name>Иван Иванов</employee-name>
      <employee-salary> 4500 лв.</employee-salary>
      <employee-position>собственик</employee-position>
    </employee>
    <employee employee-id="a1-e2">
      <employee-name>Петър Петров</employee-name>
      <employee-salary> 2500 лв.</employee-salary>
      <employee-position>мениджър</employee-position>
    </employee>
    <employee employee-id="a1-e3">
      <employee-name>Андрей Петров</employee-name>
      <employee-salary> 1500 лв.</employee-salary>
      <employee-position>асистент</employee-position>
    </employee>
    <employee employee-id="a1-e4">
      <employee-name>Йордан Баилов</employee-name>
      <employee-salary> 1500 лв.</employee-salary>
      <employee-position>асистент</employee-position>
    </employee>
    <employee employee-id="a1-e5">
      <employee-name>Пламен Иванов</employee-name>
      <employee-salary> 2500 лв.</employee-salary>
      <employee-position>механик</employee-position>
    </employee>
  </employees>
  <orders>
    <order order-id="a1-or1" ordered-products="a1-c105" processed-by="a1-e4">
      <order-date>11.12.2015</order-date>
      <total-price>110000 лв.</total-price>
      <client-info>
        <client-name>Георги Георгиев</client-name>
        <client-address>
          <city>София</city>
          <address>жк.Красна поляна, бл137А ет.4 ап.13</address>
        </client-address>
        <client-telephone>0888151455</client-telephone>
      </client-info>
    </order>
    <order order-id="a1-or2" ordered-products="a1-c102" processed-by="a1-e4">
      <order-date>14.12.2015</order-date>
      <total-price>4500лв.</total-price>
      <client-info>
        <client-name>Иван Василев</client-name>
        <client-address>
          <city>София</city>
          <address>жк.Дружба, бл127А ет.1 ап.2</address>
        </client-address>
        <client-telephone>087256855</client-telephone>
      </client-info>
    </order>
  </orders>
</auto-showroom>

=== kris18shadow/AutoShowRoom/AutoShowRoom/XmlFiles/AutoShowRoom-5.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE auto-showroom SYSTEM "AutoShowRoom.dtd">
<auto-showroom>
    <showroomName>АутоЕкзотик</showroomName>
    <cars>
        <car car-id="a5-c101" added-by="a5-e2" in-stock="t" new = "t" total-orders = "3" country-of-origin = "САЩ">
            <brand>Тесла</brand>
            <model>П75Д</model>
            <power>400 к.с.</power>
            <fuel>електричество</fuel>
            <description>Икономична, мощна и природосъобразна електрическа кола.</description>
            <class>седан</class>
            <price>155500 лв.</price>
			<color>черен</color>
			<weight>2320 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>5</seats>
        </car>
        <car car-id="a5-c102" added-by="a5-e2" in-stock="f" new = "t" total-orders = "1" country-of-origin = "Великобритания">
            <brand>Катерхам</brand>
            <model>Ц250</model>
            <power>250 к.с.</power>
            <fuel>бензин</fuel>
            <description>Спортно олекотено кабрио.</description>
            <class>кабрио</class>
            <price>44500 лв.</price>
			<color>жилт</color>
			<weight>1020 кг.</weight>
			<safety-rating> 4/5 </safety-rating>
            <seats>2</seats>
        </car>
        <car car-id="a5-c103" added-by="a5-e2" in-stock="t" new = "t" total-orders = "2" country-of-origin = "Великобритания">
            <brand>Лотус</brand>
            <model>Елиз</model>
            <power>380 к.с.</power>
            <fuel>бензин</fuel>
            <description>Британска спортна кола с две врати.</description>
            <class>купе</class>
            <price>150000 лв.</price>
			<color>зелен</color>
			<weight>1220 кг.</weight>
			<safety-rating> 4/5 </safety-rating>
            <seats>2</seats>
        </car>        
    </cars>
    <employees>
        <employee employee-id="a5-e1">
            <employee-name>Йордан Петкановски</employee-name>
			<employee-salary> 4500 лв.</employee-salary>
            <employee-position>собственик</employee-position>
        </employee>
        <employee employee-id="a5-e2">
            <employee-name>Васил Методиев</employee-name>
			<employee-salary> 4500 лв.</employee-salary>
            <employee-position>мениджър</employee-position>
        </employee>       
    </employees>
    <orders>        
        <order order-id="five-or1" ordered-products="a5-c102" processed-by="a5-e2">
            <order-date>27.12.2015</order-date>
            <total-price>44500лв.</total-price>
            <client-info>
                <client-name>Стилян Иванов</client-name>
                <client-address>
                    <city>София</city>
                    <address>жк.Симеоново, ул. Бяла бреза номер 14</address>
                </client-address>
                <client-telephone>088234559</client-telephone>
            </client-info>
        </order>
    </orders>
</auto-showroom>

=== kris18shadow/AutoShowRoom/AutoShowRoom/XmlFiles/AutoShowRoom-3.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE auto-showroom SYSTEM "AutoShowRoom.dtd">
<auto-showroom>
    <showroomName>ЛуксАуто</showroomName>
    <cars>
        <car car-id="a3-c101" added-by="a3-e3" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Япония">
            <brand>Нисан</brand>
            <model>Скайлайн</model>
            <power>324 к.с.</power>
            <fuel>бензин</fuel>
            <description>Японски спортен автомобил.</description>
            <class>купе</class>
            <price>9500 лв.</price>
			<color>сив</color>
			<weight>1320 кг.</weight>
			<safety-rating> 4/5 </safety-rating>
            <seats>2</seats>
        </car>
        <car car-id="a3-c102" added-by="a3-e2" in-stock="f" new = "f" total-orders = "2" country-of-origin = "САЩ">
            <brand>Форд</brand>
            <model>Мустанг</model>
            <power>290 к.с.</power>
            <fuel>бензин</fuel>
            <description>Американска спортна кола.</description>
            <class>купе</class>
            <price>24500 лв.</price>
			<color>сив</color>
			<weight>1720 кг.</weight>
			<safety-rating> 2/5 </safety-rating>
            <seats>4</seats>
        </car>
        <car car-id="a3-c103" added-by="a3-e2" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Германия">
            <brand>Порше</brand>
            <model>Бокстър</model>
            <power>280 к.с.</power>
            <fuel>бензин</fuel>
            <description>Спортен немски кабриолет.</description>
            <class>кабрио</class>
            <price>110000 лв.</price>
			<color>сив</color>
			<weight>1320 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>2</seats>
        </car>
        <car car-id="a3-c104" added-by="a3-e1" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Германия">
            <brand>Мерцедес</brand>
            <model>СЛК350</model>
            <power>267 к.с.</power>
            <fuel>бензин</fuel>
            <description>Луксозно малко кабрио.</description>
            <class>купе</class>
            <price>65000 лв.</price>
			<color>сив</color>
			<weight>1520 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>2</seats>
        </car> 
        <car car-id="a3-c105" added-by="a3-e1" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Германия">
            <brand>Порше</brand>
            <model>Кайен</model>
            <power>385 к.с.</power>
            <fuel>бензин</fuel>
            <description>Немски луксозен джип.</description>
            <class>джип</class>
            <price>110000 лв.</price>
			<color>сив</color>
			<weight>1920 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>5</seats>
        </car>
    </cars>
    <employees>
        <employee employee-id="a3-e1">
            <employee-name>Петър Стоянов</employee-name>
			<employee-salary> 4500 лв.</employee-salary>
            <employee-position>собственик</employee-position>
        </employee>
        <employee employee-id="a3-e2">
            <employee-name>Иван Сосков</employee-name>
			<employee-salary> 3500 лв.</employee-salary>
            <employee-position>мениджър</employee-position>
        </employee>
        <employee employee-id="a3-e3">
            <employee-name>Станимир Крайчовски</employee-name>
			<employee-salary> 3500 лв.</employee-salary>
            <employee-position>механик</employee-position>
        </employee>
    </employees>
    <orders>        
        <order order-id="a3-or1" ordered-products="a3-c102" processed-by="a3-e2">
            <order-date>01.01.2016</order-date>
            <total-price>24500лв.</total-price>
            <client-info>
                <client-name>Иван Иванов</client-name>
                <client-address>
                    <city>Плевен</city>
                    <address>жк.Свобода, бл17Б ет.5 ап.42</address>
                </client-address>
                <client-telephone>087764852</client-telephone>
            </client-info>
        </order>
    </orders>
</auto-showroom>

=== kris18shadow/AutoShowRoom/AutoShowRoom/XmlFiles/AutoShowRoom-9.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE auto-showroom SYSTEM "AutoShowRoom.dtd">
<auto-showroom>
    <showroomName>БлоуАуто</showroomName>
    <cars>
        <car car-id="a9-c101" added-by="a9-e3" in-stock="t" new = "t" total-orders = "2" country-of-origin = "Германия">
            <brand>Мерцедес</brand>
            <model>Ем-Ел</model>
            <power>453 к.с.</power>
            <fuel>бензин</fuel>
            <description>Луксозен офроудър.</description>
            <class>джип</class>
            <price>75500 лв.</price>
			<color>черен</color>
			<weight>1820 кг.</weight>
			<safety-rating> 4/5 </safety-rating>
            <seats>7</seats>
        </car>
        <car car-id="a9-c102" added-by="a9-e4" in-stock="t" new = "f" total-orders = "1" country-of-origin = "САЩ">
            <brand>Форд</brand>
            <model>Ф150</model>
            <power>190 к.с.</power>
            <fuel>дизел</fuel>
            <description>Висок американски пикап.</description>
            <class>пикап</class>
            <price>6500 лв.</price>
			<color>бял</color>
			<weight>1720 кг.</weight>
			<safety-rating> 4/5 </safety-rating>
            <seats>5</seats>
        </car>
        <car car-id="a9-c103" added-by="a9-e2" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Германия">
            <brand>БМВ</brand>
            <model>Екс5</model>
            <power>340 к.с.</power>
            <fuel>бензин</fuel>
            <description>Немски офроудър.</description>
            <class>джип</class>
            <price>18000 лв.</price>
			<color>червен</color>
			<weight>1620 кг.</weight>
			<safety-rating> 4/5 </safety-rating>
            <seats>5</seats>
        </car>
        <car car-id="a9-c104" added-by="a9-e1" in-stock="t" new = "f" total-orders = "3" country-of-origin = "Япония">
            <brand>Нисан</brand>
            <model>Патрул</model>
            <power>160 к.с.</power>
            <fuel>дизел</fuel>
            <description>Здрав и голям японски офроудър.</description>
            <class>джип</class>
            <price>15000 лв.</price>
			<color>сив</color>
			<weight>1320 кг.</weight>
			<safety-rating> 4/5 </safety-rating>
            <seats>7</seats>
        </car> 
        <car car-id="a9-c105" added-by="a9-e1" in-stock="t" new = "f" total-orders = "2" country-of-origin = "САЩ">
            <brand>Хамър</brand>
            <model>Х3</model>
            <power>385 к.с.</power>
            <fuel>бензин</fuel>
            <description>Американски офроудър с голям двигател и висок разход.</description>
            <class>джип</class>
            <price>110000 лв.</price>
			<color>зелен</color>
			<weight>1320 кг.</weight>
			<safety-rating> 4/5 </safety-rating>
            <seats>5</seats>
        </car>
    </cars>
    <employees>
        <employee employee-id="a9-e1">
            <employee-name>Иван Василев</employee-name>
			<employee-salary> 4500 лв.</employee-salary>
            <employee-position>собственик</employee-position>
        </employee>
        <employee employee-id="a9-e2">
            <employee-name>Стойко Сърменов</employee-name>
			<employee-salary> 3500 лв.</employee-salary>
            <employee-position>мениджър</employee-position>
        </employee>
        <employee employee-id="a9-e3">
            <employee-name>Сергей Петров</employee-name>
			<employee-salary> 1500 лв.</employee-salary>
            <employee-position>асистент</employee-position>
        </employee>
        <employee employee-id="a9-e4">
            <employee-name>Веселин Ирманов</employee-name>
			<employee-salary> 1500 лв.</employee-salary>
            <employee-position>механик</employee-position>
        </employee>
        <employee employee-id="a9-e5">
            <employee-name>Станимир Петров</employee-name>
			<employee-salary> 1500 лв.</employee-salary>
            <employee-position>механик</employee-position>
        </employee>
    </employees>
    <orders>        
    </orders>
</auto-showroom>

=== kris18shadow/AutoShowRoom/AutoShowRoom/XmlFiles/AutoShowRoom-8.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE auto-showroom SYSTEM "AutoShowRoom.dtd">
<auto-showroom>
    <showroomName>АутоБрон</showroomName>
    <cars>
        <car car-id="a8-c101" added-by="a8-e3" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Япония">
            <brand>Нисан</brand>
            <model>Алмера</model>
            <power>324 к.с.</power>
            <fuel>бензин</fuel>
            <description>Японски спортен седан.</description>
            <class>седан</class>
            <price>9500 лв.</price>
			<color>сив</color>
			<weight>1320 кг.</weight>
			<safety-rating> 4/5 </safety-rating>
            <seats>5</seats>
        </car>
        <car car-id="a8-c102" added-by="a8-e2" in-stock="f" new = "f" total-orders = "2" country-of-origin = "САЩ">
            <brand>Форд</brand>
            <model>Мустанг</model>
            <power>290 к.с.</power>
            <fuel>бензин</fuel>
            <description>Американска спортна кола.</description>
            <class>купе</class>
            <price>24500 лв.</price>
			<color>сив</color>
			<weight>1720 кг.</weight>
			<safety-rating> 2/5 </safety-rating>
            <seats>4</seats>
        </car>
        <car car-id="a8-c103" added-by="a8-e2" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Германия">
            <brand>Порше</brand>
            <model>Панамера</model>
            <power>280 к.с.</power>
            <fuel>бензин</fuel>
            <description>Спортен немски седан.</description>
            <class>седан</class>
            <price>110000 лв.</price>
			<color>червен</color>
			<weight>1820 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>5</seats>
        </car>
        <car car-id="a8-c104" added-by="a8-e1" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Германия">
            <brand>Мерцедес</brand>
            <model>СЛ500</model>
            <power>320 к.с.</power>
            <fuel>бензин</fuel>
            <description>Луксозно просторно кабрио.</description>
            <class>купе</class>
            <price>65000 лв.</price>
			<color>сив</color>
			<weight>1520 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>2</seats>
        </car> 
        <car car-id="a8-c105" added-by="a8-e1" in-stock="t" new = "f" total-orders = "2" country-of-origin = "Германия">
            <brand>Ауди</brand>
            <model>Ку7</model>
            <power>385 к.с.</power>
            <fuel>бензин</fuel>
            <description>Немски луксозен джип.</description>
            <class>джип</class>
            <price>110000 лв.</price>
			<color>сив</color>
			<weight>1920 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>5</seats>
        </car>
    </cars>
    <employees>
        <employee employee-id="a8-e1">
            <employee-name>Пламен Стоянов</employee-name>
			<employee-salary> 4500 лв.</employee-salary>
            <employee-position>собственик</employee-position>
        </employee>
        <employee employee-id="a8-e2">
            <employee-name>Стилян Сотиров</employee-name>
			<employee-salary> 3500 лв.</employee-salary>
            <employee-position>мениджър</employee-position>
        </employee>
        <employee employee-id="a8-e3">
            <employee-name>Николай Белурев</employee-name>
			<employee-salary> 3500 лв.</employee-salary>
            <employee-position>механик</employee-position>
        </employee>
    </employees>
    <orders>        
        <order order-id="a8-or1" ordered-products="a8-c102" processed-by="a8-e2">
            <order-date>01.01.2016</order-date>
            <total-price>24500лв.</total-price>
            <client-info>
                <client-name>Стоян Иванов</client-name>
                <client-address>
                    <city>Варна</city>
                    <address>жк.Свобода, бл17Б ет.5 ап.42</address>
                </client-address>
                <client-telephone>087864852</client-telephone>
            </client-info>
        </order>
    </orders>
</auto-showroom>
