=== kris18shadow/AutoShowRoom/AutoShowRoom/XmlFiles/AutoShowRoom.dtd
<!ELEMENT auto-showroom (showroomName, cars, employees, orders?) >
<!ELEMENT showroomName (#PCDATA) >
<!ELEMENT cars (car+) >
<!ELEMENT employees (employee+) >
<!ELEMENT orders (order*) >

<!ELEMENT car (brand, model, power, fuel, description, class, price, color, weight, safety-rating, seats) >
<!ELEMENT brand (#PCDATA) >
<!ELEMENT model (#PCDATA) >
<!ELEMENT power (#PCDATA) >
<!ELEMENT fuel (#PCDATA) >
<!ELEMENT description (#PCDATA) >
<!ELEMENT class (#PCDATA) >
<!ELEMENT price (#PCDATA) >
<!ELEMENT color (#PCDATA) >
<!ELEMENT weight (#PCDATA) >
<!ELEMENT safety-rating (#PCDATA) >
<!ELEMENT seats (#PCDATA) >

<!ELEMENT employee (employee-name, employee-salary, employee-position) >
<!ELEMENT employee-name (#PCDATA) >
<!ELEMENT employee-salary (#PCDATA) >
<!ELEMENT employee-position (#PCDATA) >

<!ELEMENT order (order-date, total-price, client-info) >
<!ELEMENT order-date (#PCDATA) >
<!ELEMENT total-price (#PCDATA) >
<!ELEMENT client-info (client-name, client-address, client-telephone?) >
<!ELEMENT client-name (#PCDATA) >
<!ELEMENT client-telephone (#PCDATA) >
<!ELEMENT client-address (city, address) >
<!ELEMENT city (#PCDATA) >
<!ELEMENT address (#PCDATA) >

<!ATTLIST car car-id ID #REQUIRED 
              added-by IDREF #REQUIRED
              in-stock (t|f) #REQUIRED
              new (t|f) #REQUIRED
              total-orders CDATA   #REQUIRED
              country-of-origin CDATA #REQUIRED>

<!ATTLIST employee employee-id ID #REQUIRED >

<!ATTLIST order order-id ID #REQUIRED
                ordered-products IDREFS #REQUIRED
                processed-by IDREF #REQUIRED>

=== kris18shadow/AutoShowRoom/AutoShowRoom/XmlFiles/AutoShowRoom-15.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE auto-showroom SYSTEM "AutoShowRoom.dtd">
<auto-showroom>
    <showroomName>АутоБран</showroomName>
    <cars>
        <car car-id="a15-c101" added-by="a15-e2" in-stock="t" new = "t" total-orders = "3" country-of-origin = "САЩ">
            <brand>Шефролет</brand>
            <model>Ампера</model>
            <power>150 к.с.</power>
            <fuel>електричество</fuel>
            <description>Икономична и природосъобразна електрическа кола.</description>
            <class>седан</class>
            <price>15500 лв.</price>
			<color>черен</color>
			<weight>2320 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>5</seats>
        </car>
        <car car-id="a15-c102" added-by="a15-e2" in-stock="f" new = "t" total-orders = "1" country-of-origin = "Великобритания">
            <brand>Лотус</brand>
            <model>Есприт</model>
            <power>250 к.с.</power>
            <fuel>бензин</fuel>
            <description>Спортно олекотено кабрио.</description>
            <class>кабрио</class>
            <price>44500 лв.</price>
			<color>жилт</color>
			<weight>1020 кг.</weight>
			<safety-rating> 4/5 </safety-rating>
            <seats>2</seats>
        </car>
        <car car-id="a15-c103" added-by="a15-e2" in-stock="t" new = "t" total-orders = "2" country-of-origin = "Великобритания">
            <brand>Лотус</brand>
            <model>Елиз</model>
            <power>380 к.с.</power>
            <fuel>бензин</fuel>
            <description>Британска спортна кола с две врати.</description>
            <class>купе</class>
            <price>150000 лв.</price>
			<color>зелен</color>
			<weight>1220 кг.</weight>
			<safety-rating> 4/5 </safety-rating>
            <seats>2</seats>
        </car>        
    </cars>
    <employees>
        <employee employee-id="a15-e1">
            <employee-name>Стоян Митокв</employee-name>
			<employee-salary> 4500 лв.</employee-salary>
            <employee-position>собственик</employee-position>
        </employee>
        <employee employee-id="a15-e2">
            <employee-name>Ивайло Петров</employee-name>
			<employee-salary> 4500 лв.</employee-salary>
            <employee-position>мениджър</employee-position>
        </employee>       
    </employees>
    <orders>        
        <order order-id="a15-or1" ordered-products="a15-c102" processed-by="a15-e2">
            <order-date>27.12.2015</order-date>
            <total-price>44500лв.</total-price>
            <client-info>
                <client-name>Иван Стоянов</client-name>
                <client-address>
                    <city>София</city>
                    <address>жк.Симеоново, ул. Бяла бреза номер 14</address>
                </client-address>
                <client-telephone>088234559</client-telephone>
            </client-info>
        </order>
    </orders>
</auto-showroom>

=== kris18shadow/AutoShowRoom/AutoShowRoom/XmlFiles/AutoShowRoom-20.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE auto-showroom SYSTEM "AutoShowRoom.dtd">
<auto-showroom>
    <showroomName>АутоИнформ</showroomName>
    <cars>
        <car car-id="a20-c101" added-by="a20-e2" in-stock="t" new = "t" total-orders = "3" country-of-origin = "САЩ">
            <brand>Додж</brand>
            <model>Челинджър</model>
            <power>400 к.с.</power>
            <fuel>бензин</fuel>
            <description>Мощен американски седан.</description>
            <class>седан</class>
            <price>155500 лв.</price>
			<color>черен</color>
			<weight>2320 кг.</weight>
			<safety-rating> 5/5 </safety-rating>
            <seats>5</seats>
        </car>
        <car car-id="a20-c102" added-by="a20-e2" in-stock="f" new = "t" total-orders = "1" country-of-origin = "Великобритания">
            <brand>Ягуар</brand>
            <model>ЕксДжей</model>
            <power>250 к.с.</power>
            <fuel>бензин</fuel>
            <description>Спортно луксозно кабрио.</description>
            <class>кабрио</class>
            <price>44500 лв.</price>
			<color>жилт</color>
			<weight>1020 кг.</weight>
			<safety-rating> 4/5 </safety-rating>
            <seats>2</seats>
        </car>
        <car car-id="a20-c103" added-by="a20-e2" in-stock="t" new = "t" total-orders = "2" country-of-origin = "Великобритания">
            <brand>Лотус</brand>
            <model>Елиз</model>
            <power>380 к.с.</power>
            <fuel>бензин</fuel>
            <description>Британска спортна кола с две врати.</description>
            <class>купе</class>
            <price>150000 лв.</price>
			<color>зелен</color>
			<weight>1220 кг.</weight>
			<safety-rating> 4/5 </safety-rating>
            <seats>2</seats>
        </car>        
    </cars>
    <employees>
        <employee employee-id="a20-e1">
            <employee-name>Стоян Петкановски</employee-name>
			<employee-salary> 4500 лв.</employee-salary>
            <employee-position>собственик</employee-position>
        </employee>
        <employee employee-id="a20-e2">
            <employee-name>Васил Методиев</employee-name>
			<employee-salary> 4500 лв.</employee-salary>
            <employee-position>мениджър</employee-position>
        </employee>       
    </employees>
    <orders>        
        <order order-id="a20-or1" ordered-products="a20-c102" processed-by="a20-e2">
            <order-date>27.12.2015</order-date>
            <total-price>44500лв.</total-price>
            <client-info>
                <client-name>Стилян Иванов</client-name>
                <client-address>
                    <city>София</city>
                    <address>жк.Симеоново, ул. Бяла бреза номер 14</address>
                </client-address>
                <client-telephone>088234559</client-telephone>
            </client-info>
        </order>
    </orders>
</auto-showroom>
